### PR TITLE
extra tag in water=reservoir + fix emergency phone

### PR DESCRIPTION
**Pull request by hakuchi**

### CODE REVIEW

**Comment by hakuchi** [comment]
@systemed do you check these pull requests or not?

**Comment by systemed** [comment]
Sure, but sometimes things slip my mind, and you can send a friendly reminder if you like. If you can provide some links (e.g. taginfo) to these being valid tags then that's helpful.

**Comment by hakuchi** [comment]
sry
Tagging is described in the Wiki and can also be found on taginfo.
https://wiki.openstreetmap.org/wiki/Tag:water%3Dreservoir
https://taginfo.openstreetmap.org/keys/reservoir_type#values

maybe I made somethin wrong into the code, so please check.

**Comment by hakuchi** [comment]
Also in this request I fixed the ref from emergency_phone, because the ref write in the value of operator.

**Pull request merged**
